Logging initialized. Writing output to 20250214_123242.log
Traceback (most recent call last):
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\main.py", line 241, in <module>
result, lpm = run_test(**config)
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\main.py", line 41, in run_test
manager.scan()
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\device_manager.py", line 76, in scan
self._instantiate(d)
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\device_manager.py", line 47, in _instantiate
definition["instance"] = PowerManager(**args)
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\power_manager.py", line 29, in __init__
self.serial_comm.open_serial()
File "C:\Users\robet\GitHubRepos\tiny\benchmark\runner\SerialCommunication.py", line 20, in open_serial
self.ser = serial.Serial(self.serial_port, self.baud_rate, timeout=1)
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
^
File "C:\Users\robet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\serial\serialwin32.py", line 33, in __init__
super(Serial, self).__init__(*args, **kwargs)
File "C:\Users\robet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\serial\serialutil.py", line 222, in __init__
self.port = port
^
^
^
^
^
^
^
^
^
File "C:\Users\robet\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\serial\serialutil.py", line 268, in port
raise ValueError('"port" must be None or a string, not {}'.format(type(port)))
ValueError
:
"port" must be None or a string, not <class 'serial_device.SerialDevice'>
